/**
 * Kode error terpusat — frontend switch berdasarkan `code`, bukan parse
 * `message` (yang bisa berubah kapan saja / berbahasa Indonesia). Tambahkan
 * kode baru di sini dulu sebelum dipakai di ApiError, supaya semua kode yang
 * beredar selalu terdaftar & bisa diaudit dari satu tempat.
 */
const ErrorCodes = {
  // Generic (mengikuti HTTP status)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',

  // Membership / Pricing / Payment
  MEMBERSHIP_REQUIRED: 'MEMBERSHIP_REQUIRED',
  MEMBERSHIP_EXPIRED: 'MEMBERSHIP_EXPIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PRICING_NOT_FOUND: 'PRICING_NOT_FOUND',
  VOUCHER_NOT_SUPPORTED: 'VOUCHER_NOT_SUPPORTED',
  WEBHOOK_INVALID_SIGNATURE: 'WEBHOOK_INVALID_SIGNATURE',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // Opportunity / Offer / Need
  OFFER_QUOTA_EXCEEDED: 'OFFER_QUOTA_EXCEEDED',
  NEED_QUOTA_EXCEEDED: 'NEED_QUOTA_EXCEEDED',
  OPPORTUNITY_QUOTA_EXCEEDED: 'OPPORTUNITY_QUOTA_EXCEEDED',

  // Chat
  SELF_CONVERSATION: 'SELF_CONVERSATION',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  NOT_CONVERSATION_PARTICIPANT: 'NOT_CONVERSATION_PARTICIPANT',
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',

  // Matching / Fraud
  SELF_MATCH: 'SELF_MATCH',
  FRAUD_DETECTED: 'FRAUD_DETECTED',

  // Verification
  NOT_VERIFIED: 'NOT_VERIFIED',

  // Admin / Account moderation
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',

  // Escrow / Transaction Permissions
  ESCROW_UNAUTHORIZED: 'ESCROW_UNAUTHORIZED',
  ESCROW_PARTY_MISMATCH: 'ESCROW_PARTY_MISMATCH',
  ESCROW_INVALID_ROLE: 'ESCROW_INVALID_ROLE',
  ESCROW_NOT_VERIFIED: 'ESCROW_NOT_VERIFIED',
  ESCROW_NOT_FOUND: 'ESCROW_NOT_FOUND',
  ESCROW_INVALID_STATE: 'ESCROW_INVALID_STATE',

  // Rate limiting & Security
  RATE_LIMITED: 'RATE_LIMITED',
  CORS_ORIGIN_NOT_ALLOWED: 'CORS_ORIGIN_NOT_ALLOWED',
  UNVERIFIED_SESSION: 'UNVERIFIED_SESSION',
  SESSION_INVALID: 'SESSION_INVALID',

  // E-commerce / Product / Cart / Order
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_QUOTA_EXCEEDED: 'PRODUCT_QUOTA_EXCEEDED',
  SELLER_MEMBERSHIP_REQUIRED: 'SELLER_MEMBERSHIP_REQUIRED',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_UNAUTHORIZED: 'ORDER_UNAUTHORIZED',
  ORDER_INVALID_STATE: 'ORDER_INVALID_STATE',
  CHECKOUT_FAILED: 'CHECKOUT_FAILED',
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
};

module.exports = ErrorCodes;